### ISSUE TITLE
TypeError: _.deepClone is not a function

### ISSUE THREAD

**Issue by reggi** [mateusmaso/underscore.deepclone#4]
Here's my code:

```
var _ = require('underscore')
_.mixin(require('underscore.deepclone'))

console.log(_.deepClone({
  "hello": {
    "foo": "bar"
  }
}))
```

Here's my error:

```
/Users/thomas/Desktop/node-mss-stitch-quantity-bridge/node_modules/underscore.deepclone/dist/underscore.deepclone.js:29
          clone[key] = _.deepClone(value);
                         ^
TypeError: _.deepClone is not a function
    at /Users/thomas/Desktop/node-mss-stitch-quantity-bridge/node_modules/underscore.deepclone/dist/underscore.deepclone.js:29:26
    at Function._.each._.forEach (/Users/thomas/Desktop/node-mss-stitch-quantity-bridge/node_modules/underscore.deepclone/node_modules/underscore/underscore.js:87:22)
    at Function.deepClone (/Users/thomas/Desktop/node-mss-stitch-quantity-bridge/node_modules/underscore.deepclone/dist/underscore.deepclone.js:27:9)
    at Object.<anonymous> (/Users/thomas/Desktop/node-mss-stitch-quantity-bridge/tests/test-requests.js:5:15)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
    at node.js:946:3
```

**Comment by mateusmaso** [comment]
that's weird, it seems that ```var _``` is somehow restricted. Try changing the underscore variable to another name and it should work.

http://stackoverflow.com/questions/10711561/why-does-requireunderscore-return-undefined-when-executed-at-the-node-js-rep

**Comment by dani7603** [comment]
Hi, the error is here:

  return {
    deepClone: function (object) {
      var clone = _.clone(object);
      _.each(clone, function (value, key) {
        if (_.isObject(value)) {
          clone[key] = _.deepClone(value);
        }
      });


_.deepClone(Value) is undefined. A fix:

  return {
    deepClone: function (object) {
      var clone = _.clone(object);
      var that = this;
      _.each(clone, function (value, key) {
        if (_.isObject(value)) {
          clone[key] = that.deepClone(value);
        }
      });

      return clone;
    }
  };
